# Generated by Django 5.0.2 on 2025-06-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("iron", "Iron"),
                            ("steel", "Steel"),
                            ("wood", "Wood"),
                            ("aluminum", "Aluminum"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(help_text="e.g. 6ft x 4ft", max_length=100),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="gates/")),
                ("description", models.TextField()),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
