# Generated by Django 5.0.2 on 2025-06-18 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gates", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gate",
            name="image",
            field=models.ImageField(
                help_text="Main/Featured image", upload_to="gates/"
            ),
        ),
        migrations.CreateModel(
            name="GateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gates/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Mark as main image"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="gates.gate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
