# Generated by Django 5.0.2 on 2025-06-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_sitesettings_adminactivitylog_userapproval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminactivitylog",
            name="admin_user",
        ),
        migrations.DeleteModel(
            name="SiteSettings",
        ),
        migrations.RemoveField(
            model_name="userapproval",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="userapproval",
            name="user",
        ),
        migrations.DeleteModel(
            name="AdminActivityLog",
        ),
        migrations.DeleteModel(
            name="UserApproval",
        ),
    ]
